pg-dbt-workshop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: kestra
      password: k3str4
      port: 5432
      dbname: kestra # or database instead of dbname
      schema: public
      threads: 4 # [optional, 1 or more]
      keepalives_idle: 0 #(#keepalives_idle): 0 # default 0, indicating the system default. See below
      connect_timeout: 10 # default 10 seconds
      retries: 5  # default 1 retry on error/timeout when opening connections
    prod:
      type: postgres
      host: localhost
      user: kestra
      password: k3str4
      port: 5432
      dbname: kestra # or database instead of dbname
      schema: production #public
      threads: 4 # [optional, 1 or more]
      keepalives_idle: 0 #(#keepalives_idle): 0 # default 0, indicating the system default. See below
      connect_timeout: 10 # default 10 seconds
      #retries: 1  # default 1 retry on error/timeout when opening connections

#bg-de-zoomcamp:
