services:
  metabase:
    image: metabase/metabase:v0.53.5.3
    container_name: metabase
    #environment:
    #  - MB_DB_FILE="/metabase-data/metabase.db"
    ports:
      - 3000:3000
    networks:
      - pg-network
    volumes:
      - metabase-data:/metabase-data/

    # depends_on:
      # pg-database:
        # condition: service_healthy

volumes:
  metabase-data:
    external: true

networks:
  pg-network:
    external: true

